### ISSUE TITLE
Slicing Example

### ISSUE THREAD

**Issue by misingnoglic** [coodict/python3-in-one-pic#3]
Why is the slicing example so bizarre? I assume this was intended for an English speaking audience (given everything else is in english), so I'm not sure a japanese slicing example does any more than show unicode support and confuse the reader in terms of actual slicing mechanics.

**Comment by rainyear** [comment]
@misingnoglic 
 Those are Chinese words. Unicode support is a very important change from py2.x to py3.x so I think it should be declared in slicing examples.

**Comment by misingnoglic** [comment]
Excuse my assuming it was Japanese. I still don't think Chinese is the best way to show this, maybe special characters with as ö would be a better way.

**Comment by mertzjames** [comment]
Slicing really has nothing to do with special characters.  That should be placed into its own example.

**Comment by rainyear** [comment]
@KronosKoderS It seems that when I try to export the MindNode format file to `*.mm` or other format those special characters break the rule. This might be a BUG from MindNode but I really need to export a `*.mm` version of it for the online version. So I'll try to work around this issue.
