### ISSUE TITLE
Override Example doesn't inherit from Parent

### ISSUE THREAD

**Issue by mertzjames** [coodict/python3-in-one-pic#9]
`class Bird:` s/b `class Bird(Animal):`

**Comment by lkreimann** [comment]
I'm not sure if this is right (my knowledge about python is very small) but I could change that and open a PR (if this repo isn't already dead ^^)

**Comment by rainyear** [comment]
@lkreimann plz~

**Comment by lkreimann** [comment]
Hopefully I can correct it the right way :) PR will come soon
